[package]
name = "dump-fnames"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cityhasher = "0.1.0"
patternsleuth = { features = ["image-pe", "process-external"], git = "https://github.com/trumank/patternsleuth" }
read-process-memory = "0.1.6"
